# Generated by Django 5.1 on 2024-08-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Email',
            field=models.EmailField(max_length=25, unique=True),
        ),
    ]
